extends Node
var game: Main
var checks: int=0
var failures: int=0
func check(ok: bool,message: String) -> void:
	checks+=1
	if ok:print("PASS: ",message)
	else:failures+=1;push_error(message)
func place(type: BuildingConfigs.BuildingType,x: int,z: int,faction: String="player") -> Building:
	var b:=Building.new();b.faction=faction;game.buildings_container.add_child(b);b.init_building(type,x,z,true)
	b.position=Vector3(x+b.footprint.x*.5,2,z+b.footprint.y*.5);game.all_buildings.append(b);EventBus.building_constructed.emit(b)
	return b
func _ready() -> void:
	SoundManager.is_muted=true
	game=load("res://scenes/Main.tscn").instantiate();add_child(game)
	game.set_process(false);game.goblin_ai.set_process(false);game.goblin_ai.expedition.set_process(false);game.time_of_day_system.set_process(false)
	var store:=place(BuildingConfigs.BuildingType.STORAGE,88,90)
	var shop:=place(BuildingConfigs.BuildingType.WORKSHOP,88,94)
	var barracks:=place(BuildingConfigs.BuildingType.BARRACKS,100,100)
	for i in range(3):place(BuildingConfigs.BuildingType.HUT,108+i*3,100)
	for i in range(2):place(BuildingConfigs.BuildingType.HUT,408+i*3,88,"goblin")
	FactionEconomy.add("player","ore",30)
	check(game.workshop_system.enqueue(shop,"sword")=="","workshop accepts a sword order")
	check(not game.production_system.permitted(shop,UnitConfigs.UnitType.WARRIOR),"workshop cannot recruit soldiers")
	check(game.production_system.enqueue(barracks,UnitConfigs.UnitType.WARRIOR)!="","knight is blocked without a completed sword")
	game.workshop_system.tick(6)
	check(EconomyManager.get_resource("sword")==0 and shop.crafting_queue[0].progress==6,"weapon production requires time")
	game.workshop_system.tick(6)
	check(EconomyManager.get_resource("sword")==1 and shop.crafting_queue.is_empty(),"one completed sword enters physical storage")
	check(game.production_system.enqueue(barracks,UnitConfigs.UnitType.WARRIOR)=="" and EconomyManager.get_resource("sword")==0,"one knight reserves exactly one sword")
	check(game.production_system.enqueue(barracks,UnitConfigs.UnitType.WARRIOR)!="","the reserved sword cannot be used twice")
	game.production_system.cancel(barracks,0)
	check(EconomyManager.get_resource("sword")==1,"cancelled recruitment returns the sword")
	var before: int=EconomyManager.get_resource("wood")
	game.workshop_system.enqueue(shop,"bow");game.workshop_system.cancel(shop,0)
	check(EconomyManager.get_resource("wood")==before,"cancelled crafting refunds ingredients once")
	game.storage_system.deposit(store,"wood",store.storage_free()-3)
	for depot in game.storage_system.buildings("player"):
		if depot!=store:game.storage_system.deposit(depot,"wood",depot.storage_free())
	var worker: Unit=game.all_units[0];worker.position=store.position+Vector3(1.5,0,0);worker.inventory={"type":"food","amount":10};worker.target=store;worker.current_order=UnitConfigs.UnitOrder.GATHER;worker.state=UnitConfigs.UnitState.RETURNING_TO_STORAGE
	game.gathering_system._update_unit_gather(worker,.1)
	check(store.storage_used()==600 and worker.inventory.amount==7,"partial delivery fills the warehouse and preserves excess cargo")
	game.gathering_system._update_unit_gather(worker,.1)
	check(worker.inventory.amount==7 and worker.state==UnitConfigs.UnitState.RETURNING_TO_STORAGE,"full warehouses leave the carrier waiting with its cargo")
	var second:=place(BuildingConfigs.BuildingType.STORAGE,90,86)
	game.gathering_system._update_unit_gather(worker,1.1)
	check(worker.target==second,"a new warehouse attracts waiting carriers")
	worker.position=second.position+Vector3(1.5,0,0);game.gathering_system._update_unit_gather(worker,.1)
	check(worker.inventory.amount==0 and second.stored_resources.get("food",0)==7,"remaining food is delivered to the new warehouse")
	var stored_food: int=EconomyManager.get_resource("food")
	FactionEconomy.spend("player",{"food":3})
	check(EconomyManager.get_resource("food")==stored_food-3 and game.storage_system.buildings("player").reduce(func(total,b):return total+b.stored_resources.get("food",0),0)==stored_food-3,"spending removes the same resources from visible stock and wallet")
	check(store.stock_visual!=null and store.stock_visual.piles.wood.get_children().any(func(n):return n.visible),"warehouse cargo is visible in separate model bays")
	var botshop:=place(BuildingConfigs.BuildingType.WORKSHOP,399,88,"goblin")
	var botbarracks:=place(BuildingConfigs.BuildingType.BARRACKS,399,92,"goblin")
	check(game.production_system.enqueue(botbarracks,UnitConfigs.UnitType.GOBLIN_ARCHER)!="","goblins also need a completed bow")
	game.workshop_system.enqueue(botshop,"bow");game.workshop_system.tick(10)
	check(game.production_system.enqueue(botbarracks,UnitConfigs.UnitType.GOBLIN_ARCHER)=="" and FactionEconomy.resources("goblin").get("bow",0)==0,"goblin recruitment consumes its own crafted bow")
	game.hud.skin.production_panel.open(shop)
	check(game.hud.skin.production_panel.cards.size()==6 and game.hud.skin.production_panel.visible,"workshop panel exposes all six real recipes")
	game.hud.skin.production_panel.open(barracks)
	check(game.hud.skin.production_panel.cards.size()==2,"barracks panel exposes the correct unit roster")
	game.hud.skin.production_panel.close()
	check(store.stock_visual.piles.values().all(func(bay):return bay.get_child_count()==9),"Blender warehouse exposes all 27 independently visible stock groups")
	game.workshop_system.enqueue(shop,"axe")
	var axes_before: int=EconomyManager.get_resource("axe")
	for depot in game.storage_system.buildings("player"):game.storage_system.deposit(depot,"wood",depot.storage_free())
	game.workshop_system.tick(8)
	check(shop.crafting_queue.size()==1 and shop.crafting_queue[0].progress==8 and EconomyManager.get_resource("axe")==axes_before,"completed tools wait in the workshop when storage is full")
	FactionEconomy.spend("player",{"wood":1});game.workshop_system.tick(0)
	check(shop.crafting_queue.is_empty() and EconomyManager.get_resource("axe")==axes_before+1,"freeing one storage slot admits exactly one completed tool")
	game.workshop_system.tick(30)
	check(EconomyManager.get_resource("axe")==axes_before+1,"completed production cannot grant duplicate tools")
	game.workshop_system.enqueue(shop,"bow")
	for depot in game.storage_system.buildings("player"):game.storage_system.deposit(depot,"wood",depot.storage_free())
	game.workshop_system.cancel(shop,0)
	check(game.storage_system.pending_returns.get("player",{}).get("wood",0)==12 and game.storage_system.pending_returns.player.get("stone",0)==2,"refunds remain pending when every warehouse is full")
	FactionEconomy.spend("player",{"wood":14});game.storage_system._process(1)
	check(game.storage_system.pending_returns.player.is_empty(),"pending refunds are restored as soon as capacity is freed")
	game.hud.skin.production_panel.open(shop)
	game.hud.skin.production_panel.cards[0].button.pressed.emit()
	check(shop.crafting_queue.size()==1,"visible recipe plus button queues a paid production order")
	game.hud.skin.production_panel.slots[0].button.pressed.emit()
	check(shop.crafting_queue.is_empty(),"visible queue card cancels its order")
	shop.is_alive=false;game.hud.skin.production_panel.refresh()
	check(not game.hud.skin.production_panel.visible,"destroying the selected workshop closes its production window")
	print("WORKSHOP STORAGE CHECKS: %d | FAILURES: %d" % [checks,failures]);get_tree().quit(failures)
